//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 08:10:42 PM MYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/4.0/sandboxlist", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.veracode.cliang.sastPlugin.objects.raw.sandboxList;
