//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.04 at 08:10:42 PM MYT 
//


package com.veracode.cliang.sastPlugin.objects.raw.sandboxList;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The sandbox type element contains the key elements and attributes
 *                 that reflect the data we store for a sandbox.
 *             
 * 
 * <p>Java class for SandboxType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SandboxType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customfield" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}CustomFieldType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sandbox_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="sandbox_name" use="required" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}LongRequiredTextType" />
 *       &lt;attribute name="owner" use="required" type="{https://analysiscenter.veracode.com/schema/4.0/sandboxlist}LongRequiredTextType" />
 *       &lt;attribute name="last_modified" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SandboxType", propOrder = {
    "customfield"
})
public class SandboxType {

    protected List<CustomFieldType> customfield;
    @XmlAttribute(name = "sandbox_id", required = true)
    protected long sandboxId;
    @XmlAttribute(name = "sandbox_name", required = true)
    protected String sandboxName;
    @XmlAttribute(name = "owner", required = true)
    protected String owner;
    @XmlAttribute(name = "last_modified", required = true)
    protected String lastModified;

    /**
     * Gets the value of the customfield property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customfield property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomfield().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldType }
     * 
     * 
     */
    public List<CustomFieldType> getCustomfield() {
        if (customfield == null) {
            customfield = new ArrayList<CustomFieldType>();
        }
        return this.customfield;
    }

    /**
     * Gets the value of the sandboxId property.
     * 
     */
    public long getSandboxId() {
        return sandboxId;
    }

    /**
     * Sets the value of the sandboxId property.
     * 
     */
    public void setSandboxId(long value) {
        this.sandboxId = value;
    }

    /**
     * Gets the value of the sandboxName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSandboxName() {
        return sandboxName;
    }

    /**
     * Sets the value of the sandboxName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSandboxName(String value) {
        this.sandboxName = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModified(String value) {
        this.lastModified = value;
    }

}
