//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 07:09:57 AM MYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://analysiscenter.veracode.com/schema/2.0/applist", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.veracode.cliang.sastPlugin.objects.raw.appList;
