//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 05:54:10 PM MYT 
//


package com.veracode.cliang.sastPlugin.objects.raw.mitigationInfo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="comment"/>
 *     &lt;enumeration value="fp"/>
 *     &lt;enumeration value="appdesign"/>
 *     &lt;enumeration value="osenv"/>
 *     &lt;enumeration value="netenv"/>
 *     &lt;enumeration value="rejected"/>
 *     &lt;enumeration value="accepted"/>
 *     &lt;enumeration value="remediated"/>
 *     &lt;enumeration value="noactiontaken"/>
 *     &lt;enumeration value="conforms"/>
 *     &lt;enumeration value="deviates"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActionTypeType")
@XmlEnum
public enum ActionTypeType {

    @XmlEnumValue("comment")
    COMMENT("comment"),
    @XmlEnumValue("fp")
    FP("fp"),
    @XmlEnumValue("appdesign")
    APPDESIGN("appdesign"),
    @XmlEnumValue("osenv")
    OSENV("osenv"),
    @XmlEnumValue("netenv")
    NETENV("netenv"),
    @XmlEnumValue("rejected")
    REJECTED("rejected"),
    @XmlEnumValue("accepted")
    ACCEPTED("accepted"),
    @XmlEnumValue("remediated")
    REMEDIATED("remediated"),
    @XmlEnumValue("noactiontaken")
    NOACTIONTAKEN("noactiontaken"),
    @XmlEnumValue("conforms")
    CONFORMS("conforms"),
    @XmlEnumValue("deviates")
    DEVIATES("deviates");
    private final String value;

    ActionTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionTypeType fromValue(String v) {
        for (ActionTypeType c: ActionTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
