//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.18 at 05:54:10 PM MYT 
//


package com.veracode.cliang.sastPlugin.objects.raw.mitigationInfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The issue type element contains the attributes and mitigation action
 *                 elements stored for a flaw.
 *             
 * 
 * <p>Java class for IssueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IssueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mitigation_action" type="{https://analysiscenter.veracode.com/schema/mitigationinfo/1.0}MitigationActionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="flaw_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="category" type="{https://analysiscenter.veracode.com/schema/mitigationinfo/1.0}LongRequiredTextType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssueType", propOrder = {
    "mitigationAction"
})
public class IssueType {

    @XmlElement(name = "mitigation_action")
    protected List<MitigationActionType> mitigationAction;
    @XmlAttribute(name = "flaw_id")
    protected Long flawId;
    @XmlAttribute(name = "category")
    protected String category;

    /**
     * Gets the value of the mitigationAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mitigationAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMitigationAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MitigationActionType }
     * 
     * 
     */
    public List<MitigationActionType> getMitigationAction() {
        if (mitigationAction == null) {
            mitigationAction = new ArrayList<MitigationActionType>();
        }
        return this.mitigationAction;
    }

    /**
     * Gets the value of the flawId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFlawId() {
        return flawId;
    }

    /**
     * Sets the value of the flawId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFlawId(Long value) {
        this.flawId = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

}
