//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 12:50:20 AM WIB 
//


package com.veracode.cliang.sastPlugin.objects.raw.buildInfo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DynamicScanType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DynamicScanType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="mp"/>
 *     &lt;enumeration value="ds"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DynamicScanType")
@XmlEnum
public enum DynamicScanType {

    @XmlEnumValue("mp")
    MP("mp"),
    @XmlEnumValue("ds")
    DS("ds");
    private final String value;

    DynamicScanType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DynamicScanType fromValue(String v) {
        for (DynamicScanType c: DynamicScanType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
