//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.14 at 08:42:26 AM MYT 
//


package com.veracode.cliang.sastPlugin.objects.raw.detailedReport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.www_veracode_com.schema.reports.export._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.www_veracode_com.schema.reports.export._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CweType }
     * 
     */
    public CweType createCweType() {
        return new CweType();
    }

    /**
     * Create an instance of {@link CweType.Description }
     * 
     */
    public CweType.Description createCweTypeDescription() {
        return new CweType.Description();
    }

    /**
     * Create an instance of {@link ManualAnalysisType }
     * 
     */
    public ManualAnalysisType createManualAnalysisType() {
        return new ManualAnalysisType();
    }

    /**
     * Create an instance of {@link AnalysisType }
     * 
     */
    public AnalysisType createAnalysisType() {
        return new AnalysisType();
    }

    /**
     * Create an instance of {@link Detailedreport }
     * 
     */
    public Detailedreport createDetailedreport() {
        return new Detailedreport();
    }

    /**
     * Create an instance of {@link SeverityType }
     * 
     */
    public SeverityType createSeverityType() {
        return new SeverityType();
    }

    /**
     * Create an instance of {@link FlawStatusType }
     * 
     */
    public FlawStatusType createFlawStatusType() {
        return new FlawStatusType();
    }

    /**
     * Create an instance of {@link CustomFieldsType }
     * 
     */
    public CustomFieldsType createCustomFieldsType() {
        return new CustomFieldsType();
    }

    /**
     * Create an instance of {@link SoftwareCompositionAnalysis }
     * 
     */
    public SoftwareCompositionAnalysis createSoftwareCompositionAnalysis() {
        return new SoftwareCompositionAnalysis();
    }

    /**
     * Create an instance of {@link ParaListType }
     * 
     */
    public ParaListType createParaListType() {
        return new ParaListType();
    }

    /**
     * Create an instance of {@link ExploitAdjustmentListType }
     * 
     */
    public ExploitAdjustmentListType createExploitAdjustmentListType() {
        return new ExploitAdjustmentListType();
    }

    /**
     * Create an instance of {@link License }
     * 
     */
    public License createLicense() {
        return new License();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link AnnotationType }
     * 
     */
    public AnnotationType createAnnotationType() {
        return new AnnotationType();
    }

    /**
     * Create an instance of {@link ExploitAdjustmentType }
     * 
     */
    public ExploitAdjustmentType createExploitAdjustmentType() {
        return new ExploitAdjustmentType();
    }

    /**
     * Create an instance of {@link ScreenshotType }
     * 
     */
    public ScreenshotType createScreenshotType() {
        return new ScreenshotType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link MitigationListType }
     * 
     */
    public MitigationListType createMitigationListType() {
        return new MitigationListType();
    }

    /**
     * Create an instance of {@link FlawType }
     * 
     */
    public FlawType createFlawType() {
        return new FlawType();
    }

    /**
     * Create an instance of {@link FilePathList }
     * 
     */
    public FilePathList createFilePathList() {
        return new FilePathList();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link FilePath }
     * 
     */
    public FilePath createFilePath() {
        return new FilePath();
    }

    /**
     * Create an instance of {@link PolicyRule }
     * 
     */
    public PolicyRule createPolicyRule() {
        return new PolicyRule();
    }

    /**
     * Create an instance of {@link MitigationType }
     * 
     */
    public MitigationType createMitigationType() {
        return new MitigationType();
    }

    /**
     * Create an instance of {@link AppendixType }
     * 
     */
    public AppendixType createAppendixType() {
        return new AppendixType();
    }

    /**
     * Create an instance of {@link Vulnerability }
     * 
     */
    public Vulnerability createVulnerability() {
        return new Vulnerability();
    }

    /**
     * Create an instance of {@link BulletItemType }
     * 
     */
    public BulletItemType createBulletItemType() {
        return new BulletItemType();
    }

    /**
     * Create an instance of {@link CustomFieldType }
     * 
     */
    public CustomFieldType createCustomFieldType() {
        return new CustomFieldType();
    }

    /**
     * Create an instance of {@link VulnerableComponentList }
     * 
     */
    public VulnerableComponentList createVulnerableComponentList() {
        return new VulnerableComponentList();
    }

    /**
     * Create an instance of {@link LicenseList }
     * 
     */
    public LicenseList createLicenseList() {
        return new LicenseList();
    }

    /**
     * Create an instance of {@link VulnerabilityList }
     * 
     */
    public VulnerabilityList createVulnerabilityList() {
        return new VulnerabilityList();
    }

    /**
     * Create an instance of {@link ViolatedRuleList }
     * 
     */
    public ViolatedRuleList createViolatedRuleList() {
        return new ViolatedRuleList();
    }

    /**
     * Create an instance of {@link FlawListType }
     * 
     */
    public FlawListType createFlawListType() {
        return new FlawListType();
    }

    /**
     * Create an instance of {@link ParaType }
     * 
     */
    public ParaType createParaType() {
        return new ParaType();
    }

    /**
     * Create an instance of {@link AnnotationListType }
     * 
     */
    public AnnotationListType createAnnotationListType() {
        return new AnnotationListType();
    }

    /**
     * Create an instance of {@link CweType.Description.Text }
     * 
     */
    public CweType.Description.Text createCweTypeDescriptionText() {
        return new CweType.Description.Text();
    }

    /**
     * Create an instance of {@link ManualAnalysisType.Modules }
     * 
     */
    public ManualAnalysisType.Modules createManualAnalysisTypeModules() {
        return new ManualAnalysisType.Modules();
    }

    /**
     * Create an instance of {@link AnalysisType.Modules }
     * 
     */
    public AnalysisType.Modules createAnalysisTypeModules() {
        return new AnalysisType.Modules();
    }

}
